# Generated by Django 4.2.5 on 2023-09-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="file",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
