# Generated by Django 4.2.5 on 2023-09-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_banner_image_alter_banner_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.section",
            ),
        ),
    ]
