# Generated by Django 4.2.5 on 2023-09-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_viewedstory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="viewedstory",
            name="is_main",
        ),
        migrations.RemoveField(
            model_name="viewedstory",
            name="section",
        ),
        migrations.AddField(
            model_name="story",
            name="is_main",
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="viewedstory",
            name="device_id",
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
