# Generated by Django 4.2.5 on 2023-09-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_remove_viewedstory_is_main_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storycontent",
            name="photo",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="storycontent",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
