# Generated by Django 4.2.4 on 2023-09-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_alter_viewedstory_device_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="product",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="section",
        ),
        migrations.RemoveField(
            model_name="volume",
            name="type",
        ),
        migrations.AddField(
            model_name="banner",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="name",
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name="banner",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
