# Generated by Django 4.2.4 on 2023-09-05 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_remove_banner_product_remove_banner_section_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="banner",
            old_name="url",
            new_name="urluz",
        ),
    ]
