# Generated by Django 4.2.4 on 2023-09-05 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_rename_url_banner_urluz"),
    ]

    operations = [
        migrations.RenameField(
            model_name="banner",
            old_name="urluz",
            new_name="url",
        ),
    ]
