# Generated by Django 4.2.4 on 2023-09-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_alter_volume_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="url",
            field=models.URLField(),
        ),
    ]
