# Generated by Django 4.2.4 on 2023-09-05 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_alter_banner_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.producttype"
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="content",
            field=models.ManyToManyField(
                related_name="story_to_content", to="product.storycontent"
            ),
        ),
        migrations.AlterField(
            model_name="viewedstory",
            name="device_id",
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.CreateModel(
            name="ProductCategoryViewed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("device_id", models.CharField(blank=True, max_length=900)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
