# Generated by Django 4.2.4 on 2023-09-05 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_alter_product_discount_alter_product_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategoryviewed",
            name="device_id",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="viewedstory",
            name="device_id",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="viewedstory",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.storycontent"
            ),
        ),
    ]
