# Generated by Django 4.2.4 on 2023-09-05 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0017_alter_productcategoryviewed_device_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategoryviewed",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_to_category",
                to="product.productcategory",
            ),
        ),
    ]
