# Generated by Django 4.2.4 on 2023-09-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0018_alter_productcategoryviewed_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=1000)),
                ("device_id", models.CharField(max_length=900)),
            ],
        ),
    ]
