# Generated by Django 4.2.4 on 2023-09-05 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0019_searchkeyword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_category",
                to="product.productcategory",
            ),
        ),
    ]
