# Generated by Django 4.2.4 on 2023-09-05 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0020_alter_section_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="section",
        ),
        migrations.AddField(
            model_name="product",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="product.section",
            ),
        ),
    ]
