# Generated by Django 4.2.4 on 2023-09-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0021_remove_product_section_product_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="product_section",
                to="product.section",
            ),
        ),
    ]
