# Generated by Django 4.2.5 on 2023-09-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0022_alter_product_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="productcategoryviewed",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="productcategoryviewed",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="storycontent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="storycontent",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="viewedstory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="viewedstory",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated at"
            ),
        ),
    ]
