# Generated by Django 4.2.5 on 2023-09-06 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0024_viewedproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="section",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="product_section",
                to="product.section",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_type",
                to="product.producttype",
            ),
        ),
        migrations.AlterField(
            model_name="viewedproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_to_product",
                to="product.product",
            ),
        ),
    ]
