# Generated by Django 4.2.5 on 2023-09-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0025_alter_product_section_alter_product_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storycontent",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
