# Generated by Django 4.2.5 on 2023-09-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0029_remove_storycontent_url_uz"),
    ]

    operations = [
        migrations.AddField(
            model_name="storycontent",
            name="file",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
