# Generated by Django 4.2.5 on 2023-09-08 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0030_storycontent_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storycontent",
            name="file",
        ),
    ]
