# Generated by Django 4.2.5 on 2023-09-10 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0031_remove_storycontent_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storycontent",
            name="url",
        ),
    ]
