# Generated by Django 4.2.4 on 2023-09-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_review_order_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='cart',
            field=models.ManyToManyField(related_name='accreditation_cart', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Is Sale'),
        ),
    ]
