# Generated by Django 4.2.4 on 2023-09-04 10:51

import apps.user.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.user.models.UserManager()),
            ],
        ),
    ]
