# Generated by Django 4.2.5 on 2023-09-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_district_created_at_alter_district_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="user.region",
                verbose_name="Region",
            ),
        ),
    ]
