# Generated by Django 4.2.5 on 2023-09-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_profile_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="to_all",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="readnotification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
