# Generated by Django 4.2.5 on 2023-09-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_notification_to_all_readnotification_is_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="to_all",
        ),
        migrations.RemoveField(
            model_name="readnotification",
            name="is_read",
        ),
    ]
